spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/org_platform
    username: app
    password: app
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

security:
  jwt:
    issuer: org-platform
    accessTokenTtlMinutes: 15
    secret: ${JWT_SECRET:change-me-in-production-this-must-be-at-least-32-characters-long}

management:
  endpoints:
    web:
      exposure:
        include: health,info
